# src/arm_moveit_config/config/moveit_controllers.yaml

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - bracket_joint
      - humerus_low_joint
      - forearm_low_joint
      - ubracket_joint
      - endeffector_joint